#! /bin/bash

# D-Bus setup
#eval `dbus-launch --sh-syntax`
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/5000/dbus/user_bus_socket
#export DBUS_SESSION_BUS_PID=335
#export DBUS_SESSION_BUS_PID=185

export XDG_RUNTIME_DIR=/var/run/user/5000

# Platform is wayland of drm-backend
export QT_QPA_PLATFORM=wayland

# Create Window OpenGL (Default gtk_drawing_area)
export NAVIT_GRAPHICS=opengl

# Graphics OpneGL Platfrom
export NAVIT_PLATFORM=wayland

# ILM library path(for hmi-launcher& genivi_mapviewer_mapviewercontrol.cxx)
#export LD_LIBRARY_PATH=/home/user/usrfs/lib:$LD_LIBRARY_PATH

# Create Layer(layer of navigation-application)
#export PATH=/home/user/usrfs/bin:$PATH
LAYER=2000
LayerManagerControl create layer $LAYER 800 480
LayerManagerControl set layer $LAYER source region 0 0 800 480
LayerManagerControl set layer $LAYER destination region 0 0 800 480
LayerManagerControl set layer $LAYER visibility 1
LayerManagerControl set screen 0 render order $LAYER

# Wayland Debug
#export WAYLAND_DEBUG=1

if [ "$WAYLAND_DEBUG" == 1 ]
then
	./run -v |& tee /tmp/wayland.log &
else
	./run -v &
fi

# wait for launch hmi-launcher
sleep 5
#SURFACE=`pgrep -f hmi-launcher`
SURFACE=2002
if [ -n $SURFACE ]; then
    LayerManagerControl set surface $SURFACE visibility 1
    LayerManagerControl set layer $LAYER render order $SURFACE
fi
